//! Core runtime for `apigate`.
//!
//! This crate contains the gateway builder, proxy runtime, routing and
//! balancing traits, pipeline context types, error model, and observability
//! events used by the public `apigate` crate.
#![warn(missing_docs)]

mod app;
mod backend;
/// Load-balancing traits and built-in balancers.
pub mod balancing;
mod error;
mod observability;
mod parts_ctx;
mod pipeline;
/// Request routing policies and policy builders.
pub mod policy;
mod proxy;
mod route;
/// Route key extraction traits and built-in routing strategies.
pub mod routing;

pub use app::{
    App, AppBuilder, ServeConfig, UpstreamConfig, run, run_router, run_router_with, run_with,
};
pub use backend::{Backend, BackendPool};
pub use error::{
    ApigateBuildError, ApigateCoreError, ApigateError, ApigateFrameworkError, ApigatePipelineError,
    BaseUriParseError, default_error_renderer,
};
pub use observability::{
    RuntimeEvent, RuntimeEventKind, RuntimeObserver, default_tracing_observer,
};
pub use parts_ctx::PartsCtx;
pub use pipeline::{
    HookResult, MapResult, PipelineFn, PipelineFuture, PipelineResult, RequestScope,
};
pub use route::RewriteSpec;
#[doc(hidden)]
pub use route::{DstChunk, RewriteTemplate, SrcSeg};

/// HTTP method used in macro-generated route definitions.
#[derive(Clone, Copy, Debug)]
pub enum Method {
    /// `GET`.
    Get,
    /// `POST`.
    Post,
    /// `PUT`.
    Put,
    /// `DELETE`.
    Delete,
    /// `PATCH`.
    Patch,
    /// `HEAD`.
    Head,
    /// `OPTIONS`.
    Options,
}

/// Macro-generated route definition.
///
/// Users normally get this from `#[apigate::service]` through `routes()`.
#[derive(Clone, Copy, Debug)]
pub struct RouteDef {
    /// HTTP method for the route.
    pub method: Method,
    /// Route path relative to the service prefix.
    pub path: &'static str,
    /// Path rewrite strategy applied before proxying.
    pub rewrite: RewriteSpec,
    /// Optional named policy overriding the service/default policy.
    pub policy: Option<&'static str>,
    /// Optional generated pipeline for hooks, validation, and mapping.
    pub pipeline: Option<PipelineFn>,
}

/// Macro-generated route collection for a service.
///
/// Pass this to [`AppBuilder::mount`] or [`AppBuilder::mount_service`].
#[derive(Clone, Copy, Debug)]
pub struct Routes {
    /// Logical service name.
    pub service: &'static str,
    /// URL path prefix mounted for the service.
    pub prefix: &'static str,
    /// Optional named policy applied to all routes in this service.
    pub policy: Option<&'static str>,
    /// Static route table generated by the service macro.
    pub routes: &'static [RouteDef],
}
