use std::sync::Arc;

use http::uri::PathAndQuery;

use crate::PipelineFn;
use crate::backend::BackendPool;
use crate::policy::Policy;

#[derive(Clone)]
pub(crate) struct RouteMeta {
    pub(crate) service: &'static str,
    pub(crate) route_path: &'static str,
    pub(crate) prefix: &'static str,
    pub(crate) rewrite: Rewrite,
    pub(crate) pool: Arc<BackendPool>,
    pub(crate) policy: Arc<Policy>,
    pub(crate) pipeline: Option<PipelineFn>,
}

#[derive(Clone, Debug)]
pub(crate) enum Rewrite {
    StripPrefix,
    Static(FixedRewrite),
    Template(&'static RewriteTemplate),
}

#[derive(Clone, Debug)]
pub(crate) struct FixedRewrite {
    raw: &'static str,
    no_query: PathAndQuery,
}

impl FixedRewrite {
    pub(crate) fn new(raw: &'static str) -> Self {
        Self {
            raw,
            no_query: PathAndQuery::from_static(raw),
        }
    }

    #[inline]
    pub(crate) fn raw(&self) -> &'static str {
        self.raw
    }

    #[inline]
    pub(crate) fn no_query(&self) -> &PathAndQuery {
        &self.no_query
    }
}

#[derive(Debug, Clone, Copy)]
#[doc(hidden)]
pub struct RewriteTemplate {
    pub src: &'static [SrcSeg],
    pub dst: &'static [DstChunk],
    pub static_len: usize,
}

#[derive(Debug, Clone, Copy)]
#[doc(hidden)]
pub enum SrcSeg {
    Lit(&'static str),
    Param,
}

#[derive(Debug, Clone, Copy)]
#[doc(hidden)]
pub enum DstChunk {
    Lit(&'static str),
    Capture { src_index: u8 },
}

/// Rewrite strategy generated by route macros.
#[derive(Clone, Copy, Debug)]
pub enum RewriteSpec {
    /// Strip the service prefix before forwarding to the upstream.
    StripPrefix,
    /// Replace the incoming path with a static path.
    Static(&'static str),
    /// Render a compile-time rewrite template.
    Template(&'static RewriteTemplate),
}
